-- Guarda las cuentas. La contraseña nueva se almacena cifrada en password_hash.
CREATE TABLE IF NOT EXISTS usuarios (
  id_usuarios INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  "contraseña" VARCHAR(255),
  password_hash TEXT
);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS rol VARCHAR(20) NOT NULL DEFAULT 'cliente';
-- Amplía los campos antiguos para aceptar los datos de las cuentas nuevas.
ALTER TABLE usuarios ALTER COLUMN nombre TYPE VARCHAR(100);
ALTER TABLE usuarios ALTER COLUMN apellido TYPE VARCHAR(100);
ALTER TABLE usuarios ALTER COLUMN email TYPE VARCHAR(255);
ALTER TABLE usuarios ALTER COLUMN "contraseña" TYPE VARCHAR(255);
ALTER TABLE usuarios ALTER COLUMN "contraseña" DROP NOT NULL;

-- Guarda los viajes que se muestran en React.
CREATE TABLE IF NOT EXISTS productos (
  id_productos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(100) UNIQUE,
  producto VARCHAR(255),
  tipo VARCHAR(100),
  precio NUMERIC(12, 2),
  slug TEXT UNIQUE,
  pais TEXT,
  foto TEXT,
  lugar TEXT,
  dias INTEGER,
  rating NUMERIC(2, 1),
  descripcion TEXT,
  numero_categoria TEXT,
  categoria TEXT,
  clase_categoria TEXT,
  descripcion_categoria TEXT
);

ALTER TABLE productos ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pais TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS foto TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS lugar TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS dias INTEGER;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS rating NUMERIC(2, 1);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS numero_categoria TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS categoria TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS clase_categoria TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS descripcion_categoria TEXT;
-- Los viajes tienen nombres, códigos y precios mayores que los campos antiguos.
ALTER TABLE productos ALTER COLUMN codigo TYPE VARCHAR(100);
ALTER TABLE productos ALTER COLUMN producto TYPE VARCHAR(255);
ALTER TABLE productos ALTER COLUMN tipo TYPE VARCHAR(100);
ALTER TABLE productos ALTER COLUMN precio TYPE NUMERIC(12, 2);
CREATE UNIQUE INDEX IF NOT EXISTS productos_slug_unico ON productos(slug);

-- Cada pedido pertenece a una cuenta y puede tener varios viajes.
CREATE TABLE IF NOT EXISTS pedidos (
  id_pedidos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMP NOT NULL DEFAULT NOW(),
  estado BOOLEAN DEFAULT FALSE,
  estado_pedido VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  id_usuarios INTEGER REFERENCES usuarios(id_usuarios)
);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS estado_pedido VARCHAR(20) NOT NULL DEFAULT 'pendiente';

-- Conserva el número del pedido que usan las tablas antiguas del proyecto.
CREATE TABLE IF NOT EXISTS numero_pedidos (
  numero_pedidos INTEGER PRIMARY KEY
);

-- Relaciona cada pedido con los viajes y cantidades que incluye.
CREATE TABLE IF NOT EXISTS detalles_productos (
  id_detalles INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedidos INTEGER REFERENCES numero_pedidos(numero_pedidos),
  cantidad INTEGER,
  precio_unitario NUMERIC(12, 2),
  id_pedidos INTEGER REFERENCES pedidos(id_pedidos),
  id_productos INTEGER REFERENCES productos(id_productos),
  tipo_servicio VARCHAR(20) NOT NULL DEFAULT 'paquete',
  fecha_salida DATE,
  dias INTEGER,
  precio_total NUMERIC(12, 2)
);

ALTER TABLE detalles_productos ADD COLUMN IF NOT EXISTS id_productos INTEGER
  REFERENCES productos(id_productos);
ALTER TABLE detalles_productos ALTER COLUMN precio_unitario TYPE NUMERIC(12, 2);
ALTER TABLE detalles_productos ADD COLUMN IF NOT EXISTS tipo_servicio VARCHAR(20) NOT NULL DEFAULT 'paquete';
ALTER TABLE detalles_productos ADD COLUMN IF NOT EXISTS fecha_salida DATE;
ALTER TABLE detalles_productos ADD COLUMN IF NOT EXISTS dias INTEGER;
ALTER TABLE detalles_productos ADD COLUMN IF NOT EXISTS precio_total NUMERIC(12, 2);

-- Guarda el total de cada compra simulada.
CREATE TABLE IF NOT EXISTS ventas (
  id_ventas INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedidos INTEGER REFERENCES numero_pedidos(numero_pedidos),
  fecha_venta TIMESTAMP NOT NULL DEFAULT NOW(),
  precio_total NUMERIC(12, 2)
);
ALTER TABLE ventas ALTER COLUMN precio_total TYPE NUMERIC(12, 2);

-- Carga los viajes iniciales; si ya existen, actualiza solo sus datos de muestra.
INSERT INTO productos (
  codigo, producto, tipo, precio, slug, pais, foto, lugar, dias, rating,
  descripcion, numero_categoria, categoria, clase_categoria, descripcion_categoria
) VALUES
  ('VIA-TOK-01', 'Tokio esencial', 'Paquete turístico', 1850000, 'tokio', 'Japón', 'japan-photo', 'TOKIO', 7, 4.9, 'Hotel 4 estrellas, desayuno, traslados y city tour.', '01', 'Asia', 'japan', 'Tradición, tecnología y paisajes increíbles.'),
  ('VIA-SEO-02', 'Seúl cultural', 'Paquete turístico', 1620000, 'seul', 'Corea del Sur', 'korea-photo', 'SEÚL', 6, 4.8, 'Hotel, desayuno, palacios históricos y paseo nocturno.', '01', 'Asia', 'japan', 'Tradición, tecnología y paisajes increíbles.'),
  ('VIA-ROM-03', 'Roma histórica', 'Paquete turístico', 1480000, 'roma', 'Italia', 'italy-photo', 'ROMA', 8, 4.9, 'Alojamiento céntrico, desayuno y visitas guiadas.', '02', 'Europa', 'europe', 'Historia, gastronomía y ciudades inolvidables.'),
  ('VIA-ATE-04', 'Islas griegas', 'Paquete turístico', 1690000, 'atenas', 'Grecia', 'greece-photo', 'ATENAS', 7, 4.8, 'Hotel, desayuno, excursión y navegación entre islas.', '02', 'Europa', 'europe', 'Historia, gastronomía y ciudades inolvidables.'),
  ('VIA-EGI-05', 'Egipto milenario', 'Paquete turístico', 1330000, 'egipto', 'Egipto', 'egypt-photo', 'EL CAIRO', 6, 4.7, 'Hotel, desayuno, pirámides, museo y excursión al Nilo.', '03', 'Aventura', 'nature', 'Naturaleza, aventura y experiencias diferentes.'),
  ('VIA-CUS-06', 'Ruta del Cusco', 'Paquete turístico', 980000, 'cusco', 'Perú', 'peru-photo', 'CUSCO', 5, 4.9, 'Hotel, desayuno, excursiones y visita a Machu Picchu.', '03', 'Aventura', 'nature', 'Naturaleza, aventura y experiencias diferentes.'),
  ('VIA-RIO-07', 'Río de Janeiro', 'Paquete turístico', 760000, 'rio', 'Brasil', 'brazil-photo', 'RÍO', 6, 4.8, 'Hotel cerca de la playa, desayuno y excursiones.', '04', 'América', 'america', 'Playas, cultura y grandes ciudades.'),
  ('VIA-CAN-08', 'Cancún Caribe', 'Paquete turístico', 1120000, 'cancun', 'México', 'mexico-photo', 'CANCÚN', 7, 4.9, 'Resort, desayuno, playa y excursión de snorkel.', '04', 'América', 'america', 'Playas, cultura y grandes ciudades.')
ON CONFLICT (codigo) DO UPDATE SET
  producto = EXCLUDED.producto,
  tipo = EXCLUDED.tipo,
  precio = EXCLUDED.precio,
  slug = EXCLUDED.slug,
  pais = EXCLUDED.pais,
  foto = EXCLUDED.foto,
  lugar = EXCLUDED.lugar,
  dias = EXCLUDED.dias,
  rating = EXCLUDED.rating,
  descripcion = EXCLUDED.descripcion,
  numero_categoria = EXCLUDED.numero_categoria,
  categoria = EXCLUDED.categoria,
  clase_categoria = EXCLUDED.clase_categoria,
  descripcion_categoria = EXCLUDED.descripcion_categoria;